function [BW,maskedImage] = finalcutt(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Jun-2022
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Close mask with disk
radius = 15;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Close mask with disk
radius = 33;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);
BW = imclearborder(BW);
se = strel('disk', 65, decomposition);
BW = imclose(BW, se);
BW = imclearborder(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end
