function [BW,maskedImage] = isolateTumor(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Jun-2022
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Close mask with disk
radius = 400;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);
radius = 10;
se = strel('disk', radius, decomposition);
BW = imdilate(BW,se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end