function [BW,maskedImage] = seggers(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 21-Jun-2022
%----------------------------------------------------


% Threshold image - manual threshold
BW = X > 68;

% Fill holes
BW = imfill(BW, 'holes');

% Clear borders
BW = imclearborder(BW);

% Close mask with disk
radius = 26;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Clear borders
BW = imclearborder(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end